name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
          
      - name: Run NPM Install
        run: npm install
      
      - name: Run Build
        run: npm run build --if-present
      
      - name: Run Test
        run: npm test
      
